name: Build Android app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        java-version: 8
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
    - name: Build
      run: ionic cordova build android --release
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
